### ISSUE TITLE
Analytical Dataset

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#11]
Dear @AaronGullickson 

 Good morning sir, I hope all is well. I think I have finished my analytical dataset. I cleaned it up and it runs without errors. I tweaked the code a little for the reorder of the reliten variable. Then I renamed it. I hope the change I made did not create other problems I don't see yet. Please let me know if I need to make corrections. Thank you so much again for your support.

Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
@Kgable Just linked this to PR #12 with comments. I think once you make those changes, it should look pretty good. The religiosity variable looks pretty good with an alpha of 0.83. 

One variable I am noting should probably be included here is age. I think you have that in this extract already.
