### ISSUE TITLE
3-way Tables and Stair Stepping

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#15]
Good morning @AaronGullickson 

  I hope all is well. I got sick over the holiday weekend and am feeling rough. However, I am trying to work through it. I think I sorted out the 3-way table and inserted it below the graph showing religiosity by education and race. I am not sure if I got it correct, it doesn't seem to add to 100 across rows. I also tried the stair-step approach and got weird results too. I put that code under the 3-way-table. All work is labeled and pushed to git. If you could take a look, I would be grateful. I will continue rough drafting the final paper this evening. I am just moving slow. Thank you again for your support. 

Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
On the three way table, you have to do the prop.table with two dimensions not one, like so:

```r
round(prop.table(table(gss$relig_affil, gss$educ_attain, gss$race),c(2,3)),3)*100
```

I would recommend doing a barplot though. This is a start:

```r
ggplot(gss, aes(x=relig_affil, y=after_stat(prop), fill=educ_attain, group=educ_attain))+
  geom_bar(position = "dodge")+
  facet_wrap(~race)+
  coord_flip()+
  theme_bw()
```

On the ordered factor, you have to assign back the result of the function to `educ_attain`:

```r
gss$educ_attain <- ordered_factor(gss$educ_attain)
```
