### ISSUE TITLE
Rough Draft 3.0

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#17]
Good morning @AaronGullickson, 

   I hope all is well. I know it has been a bit since we last spoke. I did reach out for 2 out of the last 3 weeks and went to our meeting times. I apologize for not being in touch last week. I understand you are busy and were awaiting me to send this issue. Here is the changes made to the draft. I am sure I will need to make some continued changes. I also had some questions about my models and wanted to make sure I built them correctly. Can we meet this week to discuss? Again, I apologize for the wait. Please let me know what changes I should make and I will be happy to get them completed. This will give you the basic idea though. Thank you again for all your support.

Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
Hi Kevin. Sorry to be out of touch. We should definitely meet, but with the term in full swing, I am not sure our usual time will work. Do you want to try [booking an appointment](https://calendly.com/aarongullickson/fall-2023-office-hours) in my regular OH? You can grab two back to back spots. Let me know if those times don't work.

**Comment by Kgable** [comment]
Dear Dr Gullickson,

   It is good to hear from you. I hope all is well. I understand how busy things get when the term is in full swing! I set appointments for Tuesday. See you then!

Thank you,
Kevin Gable
________________________________
