### ISSUE TITLE
Soc 413 Research Project, Religiosity by Education

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#2]
I have the raw data in my data_raw folder. This data collection assignment is complete @AaronGullickson. 
Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
Hi Kevin. Could you also do a couple of other things to complete the assignment:

* Put a paragraph in your data and methods section describing the data.
* Put a brief description of data sources in the README.md file in the `data/data_raw` directory.
* Add code to the `organize_data.qmd` that reads the data in.

**Comment by Kgable** [comment]
Dear Professor Gullickson,
  I am sorry for not reading those directions more carefully, I will get this done this evening and message you back.

Thank you,
Kevin Gable
________________________________
