### ISSUE TITLE
Preparing Analytical Dataset

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#7]
Dear professor @AaronGullickson, the analytical dataset is complete and ready for review.

Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
This looks pretty good, but I note that you are not saving the religiosity variable you created to your analytical data. It should be straightforward to go add that to your select command in the final code chunk. For grading purposes, consider this assignment done, but obviously you are going to need that!
