### ISSUE TITLE
Final Paper/Graphs

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#8]
Good afternoon @AaronGullickson , 

  I hope all is well. I was able to get rid of the NA values in my graphs. The code functions on each part with all my custom coefficients labeled. When I added an argument removing na values within the filter argument for educational attainment by sex, i was able to get rid of the NA category in the graph. But then I thought I might keep the NA in just the gender sections to reference those as a category of people who didn't specify gender. Would this make sense to do? I drop the NA in ed attainment as a general category. 
   I also added fig-"Title" and fig-cap: "figure caption" language in the graph and model codes. When I right these up in the main manuscript file it will pull and show these graphs if I refer to them via in-text citation(fig-"title") correct? Or do I need to add the code in the main manuscript? 
    I committed the code and pushed it to Git. I fixed religious attendance but left religious attendance by sex with an NA category so you can see the comparison with ed attained by sex. 

Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
Sounds good. I would not assume NA on gender means non-binary. I am surprised there are any missing gender values actually.
